// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDISbJGP8pS4rJY_E0DVuAeeR7J_lzS98I',
    appId: '1:218566165763:web:e2c3acaa131a766091d536',
    messagingSenderId: '218566165763',
    projectId: 'maya-ex',
    authDomain: 'maya-ex.firebaseapp.com',
    storageBucket: 'maya-ex.firebasestorage.app',
    measurementId: 'G-Y7SJF0RQV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTApwE8KxDpz59C03r7ooJc-Dm-dLGlUE',
    appId: '1:218566165763:android:166d9cb029de856a91d536',
    messagingSenderId: '218566165763',
    projectId: 'maya-ex',
    storageBucket: 'maya-ex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VEyWiKmBW4Q1Lz820kSd5yWSdFyMMgU',
    appId: '1:218566165763:ios:c042e5d8f4fa57e491d536',
    messagingSenderId: '218566165763',
    projectId: 'maya-ex',
    storageBucket: 'maya-ex.firebasestorage.app',
    iosBundleId: 'com.example.mayaCodingTest',
  );
}
